"""
AgriVisionAI — PDF Report Service
Generates professional crop health reports.
"""
import io
import base64
from datetime import datetime
try:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.units import mm, cm
    from reportlab.lib.colors import HexColor
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image as RLImage
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.enums import TA_CENTER, TA_LEFT
    HAS_REPORTLAB = True
    PRIMARY = HexColor("#12372A")
    EMERALD = HexColor("#2E7D32")
    LIGHT_BG = HexColor("#F5F9F5")
    WHITE = HexColor("#FFFFFF")
    DARK_TEXT = HexColor("#17211B")
    AMBER = HexColor("#F59E0B")
    RED = HexColor("#DC2626")
    GRAY = HexColor("#6B7280")
except ImportError:
    HAS_REPORTLAB = False


def _generate_fallback_pdf(data: dict) -> bytes:
    crop = data.get("crop", "Unknown")
    prediction = data.get("prediction", "N/A")
    conf = int(data.get("confidence", 0) * 100)
    sev = data.get("severity", {}).get("severity", "N/A")
    risk = data.get("risk", {}).get("risk_level", "N/A")
    pdf_text = f"""%PDF-1.4
1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj
2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj
3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >> endobj
4 0 obj << /Length 420 >>
stream
BT
/F1 18 Tf
50 780 Td
(AgriVisionAI - Crop Health Diagnosis Report) Tj
/F1 12 Tf
0 -40 Td
(Crop: {crop}) Tj
0 -20 Td
(Diagnosis: {prediction}) Tj
0 -20 Td
(Confidence: {conf}%) Tj
0 -20 Td
(Severity: {sev}) Tj
0 -20 Td
(Spread Risk: {risk}) Tj
0 -40 Td
(Generated by AgriVisionAI Platform) Tj
ET
endstream
endobj
5 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj
xref
0 6
0000000000 65535 f 
0000000009 00000 n 
0000000058 00000 n 
0000000115 00000 n 
0000000244 00000 n 
0000000720 00000 n 
trailer << /Size 6 /Root 1 0 R >>
startxref
790
%%EOF"""
    return pdf_text.encode("utf-8")


def generate_report(data: dict) -> bytes:
    """
    Generate a PDF crop health report.
    Returns PDF bytes.
    """
    if not HAS_REPORTLAB:
        return _generate_fallback_pdf(data)

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=2 * cm,
        leftMargin=2 * cm,
        topMargin=2 * cm,
        bottomMargin=2 * cm,
    )

    styles = getSampleStyleSheet()
    elements = []

    # Custom styles
    title_style = ParagraphStyle(
        "ReportTitle", parent=styles["Title"],
        fontSize=24, textColor=PRIMARY, spaceAfter=6 * mm,
        fontName="Helvetica-Bold"
    )
    subtitle_style = ParagraphStyle(
        "ReportSubtitle", parent=styles["Normal"],
        fontSize=10, textColor=GRAY, spaceAfter=10 * mm,
        alignment=TA_CENTER,
    )
    heading_style = ParagraphStyle(
        "SectionHeading", parent=styles["Heading2"],
        fontSize=14, textColor=PRIMARY, spaceBefore=8 * mm,
        spaceAfter=4 * mm, fontName="Helvetica-Bold",
    )
    body_style = ParagraphStyle(
        "BodyText", parent=styles["Normal"],
        fontSize=10, textColor=DARK_TEXT, spaceAfter=3 * mm,
        leading=14,
    )
    label_style = ParagraphStyle(
        "Label", parent=styles["Normal"],
        fontSize=9, textColor=GRAY, spaceAfter=1 * mm,
    )

    # Header
    elements.append(Paragraph("🌿 Verdra", title_style))
    elements.append(Paragraph("Detect Early. Predict Spread. Protect Yield. — Crop Health Dossier", subtitle_style))
    elements.append(Spacer(1, 4 * mm))

    # Report meta
    report_date = data.get("scan_date", datetime.now().strftime("%Y-%m-%d %H:%M"))
    farm_name = data.get("farm_name", "N/A")
    farmer_name = data.get("farmer_name", "N/A")

    meta_data = [
        ["Report Date:", report_date, "Farmer:", farmer_name],
        ["Farm:", farm_name, "Report ID:", data.get("scan_id", "N/A")],
    ]
    meta_table = Table(meta_data, colWidths=[80, 150, 60, 150])
    meta_table.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("TEXTCOLOR", (0, 0), (0, -1), GRAY),
        ("TEXTCOLOR", (2, 0), (2, -1), GRAY),
        ("TEXTCOLOR", (1, 0), (1, -1), DARK_TEXT),
        ("TEXTCOLOR", (3, 0), (3, -1), DARK_TEXT),
        ("FONTNAME", (1, 0), (1, -1), "Helvetica-Bold"),
        ("FONTNAME", (3, 0), (3, -1), "Helvetica-Bold"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    elements.append(meta_table)
    elements.append(Spacer(1, 6 * mm))

    # Diagnosis Section
    elements.append(Paragraph("Diagnosis Summary", heading_style))

    crop = data.get("crop", "Unknown")
    prediction = data.get("prediction", "Unknown")
    confidence = data.get("confidence", 0)
    is_healthy = data.get("is_healthy", False)
    severity = data.get("severity", "N/A")
    infected_pct = data.get("infected_percentage", 0)

    status = "✅ Healthy" if is_healthy else "⚠️ Disease Detected"

    diag_data = [
        ["Crop:", crop],
        ["Predicted Condition:", prediction],
        ["Confidence:", f"{confidence * 100:.1f}%"],
        ["Status:", status],
        ["Severity:", severity],
        ["Estimated Infected Area:", f"{infected_pct:.1f}%"],
    ]
    diag_table = Table(diag_data, colWidths=[150, 300])
    diag_table.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("TEXTCOLOR", (0, 0), (0, -1), GRAY),
        ("TEXTCOLOR", (1, 0), (1, -1), DARK_TEXT),
        ("FONTNAME", (1, 0), (1, -1), "Helvetica-Bold"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("BACKGROUND", (0, 0), (-1, -1), LIGHT_BG),
        ("GRID", (0, 0), (-1, -1), 0.5, HexColor("#E0E0E0")),
        ("ROUNDEDCORNERS", [4, 4, 4, 4]),
    ]))
    elements.append(diag_table)

    # Top predictions
    top_preds = data.get("top_predictions", [])
    if top_preds:
        elements.append(Spacer(1, 4 * mm))
        elements.append(Paragraph("Top Predictions:", label_style))
        for pred in top_preds:
            elements.append(Paragraph(
                f"• {pred['class_name']} — {pred['confidence'] * 100:.1f}%",
                body_style
            ))

    # Environmental Conditions
    weather = data.get("weather", {})
    if weather and weather.get("available"):
        elements.append(Paragraph("Environmental Conditions", heading_style))
        env_data = [
            ["Temperature:", f"{weather.get('temperature', 'N/A')}°C"],
            ["Humidity:", f"{weather.get('humidity', 'N/A')}%"],
            ["Rainfall (1h):", f"{weather.get('rainfall_1h', 0)} mm"],
            ["Wind Speed:", f"{weather.get('wind_speed', 'N/A')} m/s"],
            ["Conditions:", weather.get("description", "N/A").title()],
        ]
        env_table = Table(env_data, colWidths=[150, 300])
        env_table.setStyle(TableStyle([
            ("FONTSIZE", (0, 0), (-1, -1), 10),
            ("TEXTCOLOR", (0, 0), (0, -1), GRAY),
            ("TEXTCOLOR", (1, 0), (1, -1), DARK_TEXT),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]))
        elements.append(env_table)

    # Risk Assessment
    risk = data.get("risk", {})
    if risk:
        elements.append(Paragraph("Disease Spread Risk Assessment", heading_style))
        elements.append(Paragraph(
            f"<b>Risk Level: {risk.get('risk_level', 'N/A')}</b> (Score: {risk.get('risk_score', 0)}/100)",
            body_style
        ))
        factors = risk.get("factors", [])
        if factors:
            elements.append(Paragraph("Contributing Factors:", label_style))
            for factor in factors:
                elements.append(Paragraph(f"• {factor}", body_style))
        elements.append(Paragraph(risk.get("recommendation", ""), body_style))

    # Recommendations
    recs = data.get("recommendations", {})
    if recs and recs.get("found"):
        elements.append(Paragraph("Recommended Actions", heading_style))

        immediate = recs.get("immediate_actions", [])
        if immediate:
            elements.append(Paragraph("<b>Immediate Actions:</b>", body_style))
            for action in immediate:
                elements.append(Paragraph(f"• {action}", body_style))
            elements.append(Spacer(1, 2 * mm))

        preventive = recs.get("preventive_actions", [])
        if preventive:
            elements.append(Paragraph("<b>Prevention:</b>", body_style))
            for action in preventive:
                elements.append(Paragraph(f"• {action}", body_style))
            elements.append(Spacer(1, 2 * mm))

        monitoring = recs.get("monitoring_advice", [])
        if monitoring:
            elements.append(Paragraph("<b>Monitoring:</b>", body_style))
            for advice in monitoring:
                elements.append(Paragraph(f"• {advice}", body_style))
            elements.append(Spacer(1, 2 * mm))

        escalation = recs.get("expert_escalation", "")
        if escalation:
            elements.append(Paragraph("<b>Expert Escalation:</b>", body_style))
            elements.append(Paragraph(escalation, body_style))

    # Disclaimer
    elements.append(Spacer(1, 10 * mm))
    disclaimer_style = ParagraphStyle(
        "Disclaimer", parent=styles["Normal"],
        fontSize=8, textColor=GRAY, spaceAfter=2 * mm,
        leading=10, alignment=TA_CENTER,
    )
    elements.append(Paragraph(
        "AgriVisionAI provides AI-assisted crop disease screening and decision support. "
        "Predictions may not be perfect. Severe, uncertain, or commercially important cases "
        "should be verified by a qualified agricultural expert.",
        disclaimer_style
    ))
    elements.append(Paragraph(
        f"Generated by AgriVisionAI — {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        disclaimer_style
    ))

    doc.build(elements)
    return buffer.getvalue()
